@startuml

class Duck
{
    + void swim()
    + void quack()
}


class ElectronicDuck
{
    - boolean _on
    + void swim()
    + void quack()
    + void turnOn()
    + void turnOff()
}

class Pool
{
    - void quack(Duck... ducks)
    - void swim(Duck... ducks)
    + void run()
    + void main(String[] args)
}

class EPool
{
    - void quack(ElectronicDuck... ducks)
    - void swim(ElectronicDuck... ducks)
    - void turnOn(ElectronicDuck... ducks)
    - void turnOff(ElectronicDuck... ducks)
    + void run()
    + void main(String[] args)
}

Pool -. Duck
EPool -. ElectronicDuck

@enduml
